global:
  schema: "SCHEMA"
  version: "v0.1"
scopes:
  - demographics
  - demographics_historical
demographics:
  Template: "demographics.sql.tmpl"
  Filename: "demographics.sql"
  Limit: "LIMIT ?"
  Cond: "year <= 2016 and year >= 2000"
  Table: "table"
demographics_historical:
  Template: "demographics.sql.tmpl"
  Filename: "demographics.historical.sql"
  Limit: ""
  Cond: "year <= 2000 and year >= 1900"
  Table: "table"