workspace:
  base: /go
  path: /go/src/github.com/jpfairbanks/featex
pipeline:
  build:
    image: golang
    environment:
      - DBSTRING=postgres://postgres:postrgres@localhost/postgres?sslmode=verify-full
    commands:
      # - go get
      - mkdir /go/bin
      - curl https://glide.sh/get | sh
      - make get-deps
      - make build
      - cd featex && go test
      - make test
      # - go build
      # - go test

services:
#  postgres:
#    image: postgres:9.4.5
#    environment:
#      - POSTGRES_USER=myapp
