global:
  schema: "lite_synpuf2"
  version: "5"
scopes:
  - demographics
  - demographics_historical
  - features
  - condition
  - drugs
  - drug_era
  - milenial_features
  - bulk_features
demographics:
  Template: "demographics.sql.tmpl"
  Filename: "demographics.sql"
  Limit: "LIMIT ?"
  Cond: "year <= 2016 and year >= 2000"
  Table: "table"
demographics_historical:
  Template: "demographics.sql.tmpl"
  Filename: "demographics.historical.sql"
  Limit: ""
  Cond: "year <= 2000 and year >= 1900"
  Table: "table"
features:
  Template: features.sql.tmpl
  Filename: features.sql
condition:
  Template: condition.sql.tmpl
  Filename: condition.sql
drugs:
  Template: drugs.sql.tmpl
  Filename: drugs.sql
drug_era:
  Template: drug_era.sql.tmpl
  Filename: drug_era.sql
milenial_features:
  Template: constrained_features.sql.tmpl
  Filename: milenial_features.sql
  Constraint: WHERE PT.year_of_birth > 1980
  Persontable: person
bulk_features:
  Template: bulk.sql.tmpl
  Filename: bulkfeatures.sql
  Table: features
  Fields: "(job_id, person_id, cohort_start_date, cohort_end_date, concept_id, value, type)"
  Select: "select ?, person_id, cohort_start_date, cohort_end_date, 'drugs'"