global:
  schema: "mimic_v5"
  version: "5"
scopes:
  - demographics
  - demographics_historical
  - features
  - condition
  - drugs
  - drug_era
  - milenial_features
  - cohortpatients
  - bulk_features
  - bulk_drugs
  - bulk_condition
  - bulk_demographic
  - bulk_procedure
  - migration_feature_tables
demographics:
  Template: "demographics.sql.tmpl"
  Filename: "demographics.sql"
  Limit: "LIMIT ?"
  Cond: "year <= 2016 and year >= 2000"
  Table: "table"
demographics_historical:
  Template: "demographics.sql.tmpl"
  Filename: "demographics.historical.sql"
  Limit: ""
  Cond: "year <= 2000 and year >= 1900"
  Table: "table"
features:
  Template: features.sql.tmpl
  Filename: features.sql
condition:
  Template: condition.sql.tmpl
  Filename: condition.sql
drugs:
  Template: drugs.sql.tmpl
  Filename: drugs.sql
drug_era:
  Template: drug_era.sql.tmpl
  Filename: drug_era.sql
milenial_features:
  Template: constrained_features.sql.tmpl
  Filename: milenial_features.sql
  Constraint: WHERE PT.year_of_birth > 1980
  Persontable: person
migration_feature_tables:
  Template: sql/migration.tmpl
  Filename: migration/feature_tables.sql
  Results_schema: results_mimic
  Concept_schema: mimic_v5
cohortpatients:
  Template: selectwhere.sql.templ
  Filename: cohortpatients.sql
  Schema: results_mimic
  Table: cohort
  Fields: "subject_id as person_id,
  cohort_start_date as start_date,
  cohort_end_date as end_date,
  cohort_definition_id as concept_id,
  'cohort_id' as type,
  1 as value"
  Whereclause: "cohort_definition_id = $1"
bulk_features:
  Template: bulk.sql.tmpl
  Filename: bulkfeatures.sql
  Table: features
  Fields: "(job_id, person_id, cohort_start_date, cohort_end_date, concept_id, value, type)"
  Select: "select ?, person_id, cohort_start_date, cohort_end_date, 'drugs'"
bulk_drugs:
  Template: plp.sql.template
  Filename: bulk_drugs.sql
  Targettable: drug_era
  Concept: drug
  Cohorttable: "results_mimic.cohort"
  Whereclause: "WHERE cohort_definition_id= $1 and ( cohort_end_date > drug_era_start_date ) and not (drug_era_end_date < cohort_start_date)"
bulk_condition:
  Template: plp.sql.template
  Filename: bulk_condition.sql
  Targettable: condition_era
  Concept: condition
  Cohorttable: "results_mimic.cohort"
  Whereclause: "WHERE cohort_definition_id= $1 and ( cohort_end_date > condition_era_start_date ) -- and not (condition_era_end_date < cohort_start_date)"
  # historical_Whereclause: "WHERE cohort_definition_id= $1 and ( cohort_end_date > condition_era_start_date ) and (condition_era_end_date < cohort_start_date)"
bulk_procedure:
  Template: plp.sql.template
  Filename: bulk_procedure.sql
  Targettable: procedure_occurrence
  Concept: procedure
  Datefield : "procedure_date"
  Cohorttable: "results_mimic.cohort"
  Whereclause: "WHERE cohort_definition_id= $1"
bulk_demographic:
  Template: demographics_omop.sql.tmpl
  Filename: bulk_demographics.sql
  Targettable: person
  Concept: demographic
  Cohorttable: "results_mimic.cohort"
  Whereclause: "WHERE cohort_definition_id= $1"
  Gender: true
  Race: true

