features:
  demographics: {
    Filename: demographics.sql,
    bindvars: ["limit"] }
  features: {
    Filename: features.sql,
    bindvars: ["person"]
  }
  demographics_historical:
    Filename: "demographics.historical.sql"
    bindvars: []
  condition:
    Filename: "condition.sql"
    bindvars: ["person"]
  drugs:
    Filename: "drugs.sql"
    bindvars: ["person"]
  drug_era:
    Filename: "drug_era.sql"
    bindvars: ["person"]
  milenial_features:
    Filename: "milenial_features.sql"
    bindvars: []
  bulk_drugs:
    Filename: "bulk_drugs.sql"
    bindvars: ["cohort"]
  # bulk_demographics:
  #   Filename: "bulk_demographics.sql"
  #   bindvars: ["cohort"]
  bulk_condition:
    Filename: "bulk_condition.sql"
    bindvars: ["cohort"]
  bulk_procedure:
    Filename: "bulk_procedure.sql"
    bindvars: ["cohort"]
